name: C++ CI (Huffman Archive)

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build tests
      run: cmake --build build --target tests_bin -j $(nproc)

    - name: Run all tests
      run: ./build/tests_bin
